version: '3.8'

services:

  postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shortener_db
    ports:
      - "5432:5432"

  redis_cache:
    image: redis:6.2

